use ark_bdk_wallet::Wallet as ArkWallet;
use ark_client::wallet::OnchainWallet;
use bip39::Mnemonic;
use bitcoin::{
    bip32::{DerivationPath, Xpriv, Xpub},
    key::Secp256k1,
    Address, Network,
};
use std::str::FromStr;

const ALICE_MNEMONIC: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const ESPLORA_URL: &str = "https://mempool.space/api";

fn main() -> anyhow::Result<()> {
    /* 1. Convert mnemonic phrase into 64 byte seed */
    println!("Converting mnemonic phrase to seed...");
    let mnemonic: Mnemonic = ALICE_MNEMONIC.parse()?;
    let seed = mnemonic.to_seed("");

    let secp = Secp256k1::new();

    /* 2. Derive BIP32 master node from seed */
    println!("Deriving master node from seed...");
    let master_xpriv = Xpriv::new_master(Network::Bitcoin, &seed)?;

    /* 3. Derive BIP32 account node from master
     * - Purpose: Taproot (BIP86), hardened (indicated by the apostrophe)
     * - Coin type: Mainnet (indicated by '0'), hardened
     * - Account: 0 (first account), hardened
     * - Change index: 0 (for receiving funds from external addresses), non-hardened
     * - Address index: 0 (first address), non-hardened
     */
    println!("Deriving account node from master...");
    let path = DerivationPath::from_str("m/86'/0'/0'/0/0")?;
    let child_xpriv = master_xpriv.derive_priv(&secp, &path)?;

    /* 4. Extract 32-byte x-only public key */
    let xpub = Xpub::from_priv(&secp, &child_xpriv);
    let (xonly, _) = xpub.public_key.x_only_public_key();
    println!(
        "Extracted public key: ['{}']",
        hex::encode(xonly.serialize())
    );

    /* 5. Generate standard tapscript (key-path spend, no script tree) */
    println!("Generating standard tapscript...");
    let standard_address = Address::p2tr(&secp, xonly, None, Network::Bitcoin);

    /* 6. Encode standard tapscript as bech32m address */
    println!(
        "Encoded standard address at path m/86'/0'/0'/0/0: ['{}']",
        standard_address
    );

    /* 7. Validate against Arkade SDK helper */
    let ark_wallet = ArkWallet::new_from_xpriv(master_xpriv, Network::Bitcoin, ESPLORA_URL)?;
    let sdk_address = ark_wallet.get_onchain_address()?;
    println!(
        "Matches address generated by Arkade SDK helper? [{}]",
        standard_address.to_string() == sdk_address.to_string()
    );

    Ok(())
}
